#!/usr/bin/env bash
# This script creates a custom 404 page for a server

sudo apt-get -y update
sudo apt-get install -y nginx
sudo sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default
my_username=$(whoami)
sudo chown -R "$my_username":"$my_username" /var/www/html
sudo touch /var/www/html/error.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/error.html
text="error_page 404 /error.html;"
sudo sed -i "48i${text}" /etc/nginx/sites-available/default
service nginx restart
