#!/usr/bin/env bash
# This script configures an Nginx server with a custom header
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default
my_username=$(whoami)
sudo chown -R "$my_username":"$my_username" /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
host=$(hostname)
sudo sed -i "51i add_header X-Served-By \"$host\";" /etc/nginx/sites-available/default
sudo service nginx start
