#!/usr/bin/env bash
# This script Installs and sets up haproxy

sudo apt-get -y update
sudo apt-get install -y haproxy
echo 'ENABLED=1' >> sudo tee /etc/default/haproxy

sudo sed -i "28i timeout http-request 10s" /etc/haproxy/haproxy.cfg
echo "

frontend myfrontend
	bind 0.0.0.0:80
	default_backend myservers

backend myservers
	balance roundrobin
        server 344136-web-01 100.24.205.80
        server 344136-web-02 54.85.130.183
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
