#!/usr/bin/env bash
# This script Installs and sets up haproxy

sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
sudo sed -i "28i timeout http-request 10s" /etc/haproxy/haproxy.cfg
echo "

frontend myfrontend
	bind 0.0.0.0:80
	default_backend myservers

backend myservers
	balance roundrobin
	server server1 100.26.168.110
	server server2 34.207.222.84
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
