#!/usr/bin/env bash
# This pings an IP address passed as an argument
ip_address="$1"
if [ -z "$1" ]; then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi
ping -c 5 "$ip_address"
