#!/usr/bin/env bash
# This script ensures Nginx installation can listen on port 80
apt-get -y update
apt-get -y install nginx curl
sed -i 's|listen 8080 default_server;|listen 80;|' /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
