#!/usr/bin/env bash
# This script ensures Nginx installation can listen on port 80
sed -i 's|listen 8080 default_server;|listen 80;|' /etc/nginx/sites-available/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
