#!/usr/bin/env bash
# This script ensures Nginx installation can listen on port 80
sudo ln -sf /etc/nginx/sites-available/example.com /etc/nginx/sites-enabled/
sudo service start nginx
kill "$(pgrep 'nginx' | head -1)"
