#!/usr/bin/env bash
#This displays all the files in the working directory

for file in *; do
  if [ -f "$file" ] && [[ "$file" != .* ]]; then
    name=$(echo "$file" | cut -d'-' -f2-)
    echo "$name"
  fi
done
