#!/usr/bin/env bash
# This configures an Ubuntu server with the specified requirements

line=$(grep -n "" /etc/hosts | grep localhost | grep -v ip6| cut -d : -f 1)

cp /etc/hosts ~/hosts.new
if [ -n "$line" ]; then
    sed -i "${line}d" ~/hosts.new
fi

sed -i '2i 8.8.8.8   facebook.com'  ~/hosts.new
sed -i '1i 127.0.0.2   localhost'  ~/hosts.new
cp -f ~/hosts.new /etc/hosts
